name: mi_super_tienda
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.9
  flutter_zoom_drawer: ^3.0.3
  carousel_slider: ^5.0.0
  flutter_image_compress: ^1.0.0
  path_provider: ^2.0.11
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png 
    - assets/fondoweb.jpg

    - assets/images/supermercado1.png
    - assets/images/supermercado2.png
    - assets/images/supermercado3.png
    - assets/images/supermercado4.png
    - assets/images/supermercado5.png
    - assets/images/supermercado6.png
    - assets/images/supermercado7.png
    - assets/images/supermercado8.png
    - assets/images/supermercado9.png
    - assets/images/supermercado10.png
    - assets/images/supermercado11.png
    - assets/images/supermercado12.png

    - assets/categorias/tecnologia.png
    - assets/categorias/deportes.jpg
    - assets/categorias/moda.jpg
    - assets/categorias/hogar.jpg
    - assets/categorias/alimentos.jpg
    - assets/categorias/juguetes.jpg

    - assets/productos/producto1.jpg
    - assets/productos/producto2.jpg
    - assets/productos/producto3.jpg
    - assets/productos/producto4.jpg
    - assets/productos/producto5.jpg
    - assets/productos/producto6.jpg
    - assets/productos/producto7.jpg
    - assets/productos/producto8.jpg
    - assets/productos/producto9.jpg
    - assets/productos/producto10.jpg
    
  uses-material-design: true



 